#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "CHANGE_ME"
primary_region = "fra"
swap_size_mb = 128

[build]
  image = "ghcr.io/niklasrosenstein/headscale-fly-io:0.2.3-headscale-0.23.0"

[deploy]
  strategy = "immediate"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[[metrics]]
  port = 8081
  path = "/metrics"
  processes = ["app"]

[[vm]]
  size = "shared-cpu-1x"

# [env]
#   HEADSCALE_SERVER_DOMAIN = "vpn.example.com"
#   HEADSCALE_OIDC_ISSUER = "https://mykeycloak.org/realms/main"
#   HEADSCALE_OIDC_CLIENT_ID = "headscale"
