name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
      - name: Renovate
        uses: renovatebot/github-action@v40.2.2
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
